#!/usr/bin/env bash

export PGPASSWORD=postgres
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

sudo service postgresql start

cd ~/work/tomcat/bin
chmod +x ~/work/tomcat/bin/catalina.sh
bash -c "~/work/tomcat/bin/catalina.sh run"