#!/usr/bin/env bash

export PGPASSWORD=postgres
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

sudo service postgresql start

cd ~/work/tomcat/bin
chmod +x ~/work/tomcat/bin/*.sh
# Docker console includes Tomcat console
bash -c "~/work/tomcat/bin/catalina.sh run"
#  direct shell alternative
#bash -c "~/work/tomcat/bin/startup.sh"
#bash -l